version: '3.8'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_TENANT_ID: e2e47d29-6130-4655-a68a-f8497e228f92
      NEXTAUTH_SECRET: 0ZxVA+qmEeBvP2u8trVQqS/FlphymZqH4xTY0qOJq7c=
    depends_on:
      - db

  db:
    image: sqlite:latest  # Use an appropriate database image for your app
    volumes:
      - db-data:/var/lib/sqlite

volumes:
  db-data:
